image: bellsoft/liberica-openjdk-alpine:8

variables:
  MAVEN_CLI_OPTS: "--show-version --batch-mode \
    -Dmaven.repo.local=.m2/repository \
    -Duser.timezone=Asia/Jakarta \
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  RELEASE_DIGIT: 1
  HOTFIX_DIGIT: 2

cache:
  paths:
    - .m2/repository/

default:
  before_script:
    - apk add --update --no-cache git
    - git --version
    - git remote set-url --push origin "https://${GITLAB_USER_LOGIN}:${READ_WRITE_REPOSITORY_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

stages:
  - build
  - test
  - snapshot
  - release

build:
  stage: build
  script: ./mvnw $MAVEN_CLI_OPTS test-compile
  allow_failure: false
  only:
    - develop

test:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  allow_failure: false
  only:
    - develop

deploy-jar-snapshot:
  stage: snapshot
  dependencies:
    - test
  script: ./mvnw $MAVEN_CLI_OPTS deploy -DskipTests -s .m2/settings.xml
  allow_failure: false
  only:
    - develop

release:
  stage: release
  dependencies:
    - test
  script:
    - ./mvnw $MAVEN_CLI_OPTS gitflow:release -DversionDigitToIncrement=$RELEASE_DIGIT -DargLine=$MAVEN_CLI_OPTS
  allow_failure: false
  only:
    - develop
  when: manual

deploy-jar-release:
  stage: release
  dependencies:
    - release
  script: ./mvnw $MAVEN_CLI_OPTS deploy -DskipTests -s .m2/settings.xml
  allow_failure: false
  only:
    - master

hotfix-start:
  stage: release
  dependencies:
    - release
  script:
    - ./mvnw $MAVEN_CLI_OPTS gitflow:hotfix-start -DhotfixVersionDigitToIncrement=$HOTFIX_DIGIT -DargLine=$MAVEN_CLI_OPTS
    - git push origin HEAD
  allow_failure: false
  only:
    - master
  when: manual

# Inspired from here: https://github.com/viesure/blog-gitflow-maven/blob/master/.gitlab-ci.yml
hotfix-finish:
  stage: release
  dependencies:
    - hotfix-start
  script:
    # Manually fix the git refs. gitflow plugin uses the heads ref, but we do not have it set up locally, however we have the remote ref
    - git symbolic-ref refs/heads/$CI_COMMIT_BRANCH refs/remotes/origin/$CI_COMMIT_BRANCH
    - ./mvnw $MAVEN_CLI_OPTS gitflow:hotfix-finish -DhotfixBranch=$CI_COMMIT_BRANCH -DargLine=$MAVEN_CLI_OPTS
  allow_failure: false
  only:
    - /^hotfix\/.*$/
  when: manual
